import type { User, Project, Task, TaskStatus, Comment } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Alex Doe', email: 'alex@example.com', password: 'password-admin', avatarUrl: 'https://i.pravatar.cc/150?u=user-1', role: 'Admin' },
  { id: 'user-2', name: 'Jane Smith', email: 'jane@example.com', password: 'password-manager', avatarUrl: 'https://i.pravatar.cc/150?u=user-2', role: 'Manager' },
  { id: 'user-3', name: 'Sam Wilson', email: 'sam@example.com', password: 'password-member', avatarUrl: 'https://i.pravatar.cc/150?u=user-3', role: 'Team Member' },
  { id: 'user-4', name: 'Casey Jones', email: 'casey@example.com', password: 'password-member2', avatarUrl: 'https://i.pravatar.cc/150?u=user-4', role: 'Team Member' },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website to improve user experience and refresh the branding.',
    ownerId: 'user-2',
    memberIds: ['user-1', 'user-2', 'user-3', 'user-4'],
  },
  {
    id: 'proj-2',
    name: 'Mobile App Launch',
    description: 'Develop and launch the new mobile application for iOS and Android platforms.',
    ownerId: 'user-1',
    memberIds: ['user-1', 'user-2', 'user-3'],
  },
  {
    id: 'proj-3',
    name: 'Q3 Marketing Campaign',
    description: 'Plan and execute the marketing campaign for the third quarter, focusing on social media engagement.',
    ownerId: 'user-2',
    memberIds: ['user-1', 'user-2', 'user-4'],
  },
];

const comments: Comment[] = [
    {
        id: 'comment-1',
        taskId: 'task-1',
        userId: 'user-2',
        content: "This is a critical first step. Let's make sure we get the wireframes right.",
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'comment-2',
        taskId: 'task-1',
        userId: 'user-3',
        content: "Agreed. I've uploaded some initial sketches for the homepage. Feedback welcome!",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
     {
        id: 'comment-3',
        taskId: 'task-1',
        userId: 'user-2',
        content: "Looks great, Sam! Just a few thoughts: can we make the CTA button more prominent? Also, let's consider adding a video banner. Otherwise, great start.",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
     {
        id: 'comment-4',
        taskId: 'task-1',
        userId: 'user-3',
        content: "Good points. I'll make those adjustments. New version coming tomorrow AM.",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    }
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    creatorId: 'user-2',
    title: 'Design initial mockups and wireframes',
    description: 'Create detailed wireframes for the new homepage and key landing pages.',
    status: 'In Progress',
    priority: 'High',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-3'],
    comments: comments,
    attachments: [{id: 'attach-1', fileName: 'initial_sketches.pdf', url: '#'}],
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    creatorId: 'user-2',
    title: 'Develop user authentication flow',
    description: 'Implement sign-up, sign-in, and password reset functionality.',
    status: 'In Progress',
    priority: 'High',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-4'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    creatorId: 'user-1',
    title: 'Set up staging environment',
    description: 'Configure the staging server and deployment pipeline.',
    status: 'Todo',
    priority: 'Medium',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-4'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    creatorId: 'user-2',
    title: 'Finalize branding style guide',
    description: 'Choose final color palette, typography, and logo variations.',
    status: 'Done',
    priority: 'Medium',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-2'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-5',
    projectId: 'proj-2',
    creatorId: 'user-1',
    title: 'Market research for iOS app features',
    description: 'Analyze competitor apps and identify key features for MVP.',
    status: 'Done',
    priority: 'High',
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-3'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    creatorId: 'user-1',
    title: 'Build API endpoints for user profiles',
    description: 'Create RESTful endpoints for creating, reading, and updating user data.',
    status: 'In Progress',
    priority: 'High',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-4'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    creatorId: 'user-2',
    title: 'Design onboarding screens',
    description: 'Design a seamless and engaging onboarding experience for new users.',
    status: 'Todo',
    priority: 'Medium',
    dueDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-3'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-8',
    projectId: 'proj-3',
    creatorId: 'user-2',
    title: 'Identify target audience for social media',
    description: 'Define the primary and secondary target audiences for the campaign.',
    status: 'Done',
    priority: 'High',
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-4'],
    comments: [],
    attachments: [],
  },
  {
    id: 'task-9',
    projectId: 'proj-3',
    creatorId: 'user-2',
    title: 'Create content calendar',
    description: 'Schedule posts for Instagram, Twitter, and Facebook for the next 30 days.',
    status: 'Todo',
    priority: 'Medium',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    assigneeIds: ['user-4'],
    comments: [],
    attachments: [],
  },
];

export const statuses: TaskStatus[] = ['Todo', 'In Progress', 'Done'];
